<?php
header('Content-type: text/plain');


// Read the main list
$tree = @file_get_contents('http://cgit.freedesktop.org/libreoffice/core/tree/');
if (! $tree) {
	die('No connection to cgit!');
}
preg_match_all('!<a class=\'ls-dir\' href=\'/libreoffice/core/tree/([-_a-zA-Z0-9]+)\'>!', $tree, $matches);
unset ($tree);
natcasesort($matches[1]);


// Enable this for faster testing
//$matches[1] = array('scripting', 'editeng', 'framework');


// Read the READMEs
echo "READING:\n";

$modules = array();
foreach ($matches[1] as $name) {
	$readme = null;
	$has_doxygen = false;

	echo " - {$name}\n";

	$readme = @file_get_contents("http://cgit.freedesktop.org/libreoffice/core/plain/{$name}/README");
	if (strpos($readme, '<html') !== false) $readme = '';

	if (! $readme) {
		$readme = @file_get_contents("http://cgit.freedesktop.org/libreoffice/core/plain/{$name}/readme.txt");
		if (strpos($readme, '<html') !== false) $readme = '';
	}

	if (! $readme) {
		$no_readme[] = $name;
		continue;
	}


	$fp = @fopen("http://docs.libreoffice.org/{$name}/html/classes.html", 'r');
	if ($fp) {
		$has_doxygen = true;
		fclose($fp);
	}

	$paras = explode("\n\n", $readme);
	$short = $paras[0];
	$modules[$name] = array($short, $readme, $has_doxygen);

	unset ($short, $paras, $readme);
}


// Nuke old docs
echo "NUKING OLD DOCS.\n";
@mkdir('data');
$files = glob('data/*');
foreach ($files as $f) {
	unlink($f);
}


// Generate the HTML documents
echo "GENERATING HTML:\n";

$tag = '';

$text = head('LibreOffice Modules', null);
foreach ($modules as $name => $info) {
	$text .= "<h2><a href=\"{$name}.htm\">{$name}</a></h2>\n";
	$text .= proc_text($info[0]);
}
if (@count($no_readme)) {
	$text .= "<p>&nbsp;</p><p>READMEs were not available for these modules:</p><ul>";
	foreach ($no_readme as $name) {
		$text .= "<li><a href=\"http://cgit.freedesktop.org/libreoffice/core/tree/{$name}\">{$name}</a></li>";
	}
	$text .= "</ul>";
}
$text .= foot();
echo " - index.htm\n";
file_put_contents('data/index.htm', $text);

foreach ($modules as $name => $info) {
	$text = head($name, "<a href=\"index.htm\">LibreOffice</a> &raquo; {$name}");
	$text .= "<p><b>View module in:</b>";
	$text .= " &nbsp; <a href=\"http://cgit.freedesktop.org/libreoffice/core/tree/{$name}\">cgit</a>";
	if ($info[2]) {
		$text .= " &nbsp; <a href=\"http://docs.libreoffice.org/{$name}/html/classes.html\">Doxygen</a>";
	}
	$text .= "</p>";
	$text .= "<p>&nbsp;</p>";
	$text .= proc_text($info[1]);
	$text .= foot();
	echo " - {$name}.htm\n";
	file_put_contents("data/{$name}.htm", $text);
}


echo "ALL DONE!\n";



function head($title, $breadcrumb) {
	return "<html>
<head>
	<title>{$title}</title>

	<style>
	* { margin: 0; padding: 0; }
	body { font-family: sans-serif; font-size: 12px; }
	#head { padding: 20px; background: #ABC0F4; }
	#head a { color: #000; }
	#body { padding: 20px; }
	#foot { padding: 10px; font-size: 9px; border-top: 1px #ABC0F4 solid; margin-top: 25px; }
	p { line-height: 1.7em; margin-bottom: 1em; }
	pre { margin-bottom: 0.5em; }
	.multi-col { -moz-column-width: 13em; -webkit-column-width: 13em; -moz-column-gap: 1em; -webkit-column-gap: 1em; }
	h1 {margin-bottom: 0.5em;}
	h2,h3,h4 { margin: 1.3em 0 0.5em 0; }
	ul, ol { margin: 0.5em 1.5em; }
	</style>
</head>
<body>
	<div id=\"head\">
	<h1>{$title}</h1>
	<p>{$breadcrumb}</p>
	</div>
	<div id=\"body\">\n\n";
}

function foot() {
	return "\n\n</div><div id=\"foot\">Generated by Libreoffice Module Description Tool v1.0.0.1</small></div>\n</body>\n</html>";
}


function proc_text($text) {
	// Local links [[...]]
	$text = preg_replace('!\[\[([-_a-zA-Z0-9]+)\]\]!', '<a href="$1.htm">$1</a>', $text);

	// Git links [git:...]
	$text = preg_replace('!\[git:([^]]+)\]!', '<a href="http://cgit.freedesktop.org/libreoffice/core/tree/$1">$1</a>', $text);

	// Other remote links [...]
	$text = preg_replace('!\[([^]]+)\]!', '<a href="$1">$1</a>', $text);

	// Headings
	$text = preg_replace('!====([^=]+)====!', '<h4>$1</h4>', $text);
	$text = preg_replace('!===([^=]+)===!', '<h3>$1</h3>', $text);
	$text = preg_replace('!==([^=]+)==!', '<h2>$1</h2>', $text);

	// Paragraphs
	$text = '<p>' . preg_replace('!\n\n+!', '</p><p>', $text) . '</p>';

	return $text;
}
